steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t northamerica-south1-docker.pkg.dev/iron-radio-450121-s8/store-registry/store-products-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/iron-radio-450121-s8/store-registry/store-products-ms',
      ]

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/910467791073/secrets/products_database_url/versions/1
      env: 'DATABASE_URL'
